/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/apis/aci.fabricattachment/v1"
	acifabricattachmentv1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/applyconfiguration/aci.fabricattachment/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/fabricattachment/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeFabricNetworkL3PeersGetter has a method to return a NodeFabricNetworkL3PeerInterface.
// A group's client should implement this interface.
type NodeFabricNetworkL3PeersGetter interface {
	NodeFabricNetworkL3Peers() NodeFabricNetworkL3PeerInterface
}

// NodeFabricNetworkL3PeerInterface has methods to work with NodeFabricNetworkL3Peer resources.
type NodeFabricNetworkL3PeerInterface interface {
	Create(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.CreateOptions) (*v1.NodeFabricNetworkL3Peer, error)
	Update(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.UpdateOptions) (*v1.NodeFabricNetworkL3Peer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NodeFabricNetworkL3Peer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NodeFabricNetworkL3PeerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeFabricNetworkL3Peer, err error)
	Apply(ctx context.Context, nodeFabricNetworkL3Peer *acifabricattachmentv1.NodeFabricNetworkL3PeerApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NodeFabricNetworkL3Peer, err error)
	NodeFabricNetworkL3PeerExpansion
}

// nodeFabricNetworkL3Peers implements NodeFabricNetworkL3PeerInterface
type nodeFabricNetworkL3Peers struct {
	client rest.Interface
}

// newNodeFabricNetworkL3Peers returns a NodeFabricNetworkL3Peers
func newNodeFabricNetworkL3Peers(c *AciV1Client) *nodeFabricNetworkL3Peers {
	return &nodeFabricNetworkL3Peers{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeFabricNetworkL3Peer, and returns the corresponding nodeFabricNetworkL3Peer object, and an error if there is any.
func (c *nodeFabricNetworkL3Peers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	result = &v1.NodeFabricNetworkL3Peer{}
	err = c.client.Get().
		Resource("nodefabricnetworkl3peers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeFabricNetworkL3Peers that match those selectors.
func (c *nodeFabricNetworkL3Peers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NodeFabricNetworkL3PeerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeFabricNetworkL3PeerList{}
	err = c.client.Get().
		Resource("nodefabricnetworkl3peers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeFabricNetworkL3Peers.
func (c *nodeFabricNetworkL3Peers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("nodefabricnetworkl3peers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeFabricNetworkL3Peer and creates it.  Returns the server's representation of the nodeFabricNetworkL3Peer, and an error, if there is any.
func (c *nodeFabricNetworkL3Peers) Create(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.CreateOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	result = &v1.NodeFabricNetworkL3Peer{}
	err = c.client.Post().
		Resource("nodefabricnetworkl3peers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeFabricNetworkL3Peer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeFabricNetworkL3Peer and updates it. Returns the server's representation of the nodeFabricNetworkL3Peer, and an error, if there is any.
func (c *nodeFabricNetworkL3Peers) Update(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.UpdateOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	result = &v1.NodeFabricNetworkL3Peer{}
	err = c.client.Put().
		Resource("nodefabricnetworkl3peers").
		Name(nodeFabricNetworkL3Peer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeFabricNetworkL3Peer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeFabricNetworkL3Peer and deletes it. Returns an error if one occurs.
func (c *nodeFabricNetworkL3Peers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("nodefabricnetworkl3peers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeFabricNetworkL3Peers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("nodefabricnetworkl3peers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeFabricNetworkL3Peer.
func (c *nodeFabricNetworkL3Peers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeFabricNetworkL3Peer, err error) {
	result = &v1.NodeFabricNetworkL3Peer{}
	err = c.client.Patch(pt).
		Resource("nodefabricnetworkl3peers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeFabricNetworkL3Peer.
func (c *nodeFabricNetworkL3Peers) Apply(ctx context.Context, nodeFabricNetworkL3Peer *acifabricattachmentv1.NodeFabricNetworkL3PeerApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	if nodeFabricNetworkL3Peer == nil {
		return nil, fmt.Errorf("nodeFabricNetworkL3Peer provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nodeFabricNetworkL3Peer)
	if err != nil {
		return nil, err
	}
	name := nodeFabricNetworkL3Peer.Name
	if name == nil {
		return nil, fmt.Errorf("nodeFabricNetworkL3Peer.Name must be provided to Apply")
	}
	result = &v1.NodeFabricNetworkL3Peer{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("nodefabricnetworkl3peers").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
