/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BGPPeerPrefixPolicyApplyConfiguration represents an declarative configuration of the BGPPeerPrefixPolicy type for use
// with apply.
type BGPPeerPrefixPolicyApplyConfiguration struct {
	Name        *string `json:"name,omitempty"`
	MaxPrefixes *int    `json:"maxPrefixes,omitempty"`
	Action      *string `json:"action,omitempty"`
}

// BGPPeerPrefixPolicyApplyConfiguration constructs an declarative configuration of the BGPPeerPrefixPolicy type for use with
// apply.
func BGPPeerPrefixPolicy() *BGPPeerPrefixPolicyApplyConfiguration {
	return &BGPPeerPrefixPolicyApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BGPPeerPrefixPolicyApplyConfiguration) WithName(value string) *BGPPeerPrefixPolicyApplyConfiguration {
	b.Name = &value
	return b
}

// WithMaxPrefixes sets the MaxPrefixes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPrefixes field is set to the value of the last call.
func (b *BGPPeerPrefixPolicyApplyConfiguration) WithMaxPrefixes(value int) *BGPPeerPrefixPolicyApplyConfiguration {
	b.MaxPrefixes = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *BGPPeerPrefixPolicyApplyConfiguration) WithAction(value string) *BGPPeerPrefixPolicyApplyConfiguration {
	b.Action = &value
	return b
}
