/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FabricL3PeersApplyConfiguration represents an declarative configuration of the FabricL3Peers type for use
// with apply.
type FabricL3PeersApplyConfiguration struct {
	Encap         *int  `json:"encap,omitempty"`
	FabricPodId   *int  `json:"podId,omitempty"`
	FabricNodeIds []int `json:"fabricNodeIds,omitempty"`
}

// FabricL3PeersApplyConfiguration constructs an declarative configuration of the FabricL3Peers type for use with
// apply.
func FabricL3Peers() *FabricL3PeersApplyConfiguration {
	return &FabricL3PeersApplyConfiguration{}
}

// WithEncap sets the Encap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encap field is set to the value of the last call.
func (b *FabricL3PeersApplyConfiguration) WithEncap(value int) *FabricL3PeersApplyConfiguration {
	b.Encap = &value
	return b
}

// WithFabricPodId sets the FabricPodId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FabricPodId field is set to the value of the last call.
func (b *FabricL3PeersApplyConfiguration) WithFabricPodId(value int) *FabricL3PeersApplyConfiguration {
	b.FabricPodId = &value
	return b
}

// WithFabricNodeIds adds the given value to the FabricNodeIds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FabricNodeIds field.
func (b *FabricL3PeersApplyConfiguration) WithFabricNodeIds(values ...int) *FabricL3PeersApplyConfiguration {
	for i := range values {
		b.FabricNodeIds = append(b.FabricNodeIds, values[i])
	}
	return b
}
