/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	acifabricattachmentv1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/apis/aci.fabricattachment/v1"
)

// FabricL3NetworkApplyConfiguration represents an declarative configuration of the FabricL3Network type for use
// with apply.
type FabricL3NetworkApplyConfiguration struct {
	PrimaryNetworkApplyConfiguration `json:",inline"`
	Subnets                          []FabricL3SubnetApplyConfiguration `json:"subnets,omitempty"`
}

// FabricL3NetworkApplyConfiguration constructs an declarative configuration of the FabricL3Network type for use with
// apply.
func FabricL3Network() *FabricL3NetworkApplyConfiguration {
	return &FabricL3NetworkApplyConfiguration{}
}

// WithL3OutName sets the L3OutName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the L3OutName field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithL3OutName(value string) *FabricL3NetworkApplyConfiguration {
	b.L3OutName = &value
	return b
}

// WithL3OutOnCommonTenant sets the L3OutOnCommonTenant field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the L3OutOnCommonTenant field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithL3OutOnCommonTenant(value bool) *FabricL3NetworkApplyConfiguration {
	b.L3OutOnCommonTenant = &value
	return b
}

// WithUseExistingL3Out sets the UseExistingL3Out field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseExistingL3Out field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithUseExistingL3Out(value bool) *FabricL3NetworkApplyConfiguration {
	b.UseExistingL3Out = &value
	return b
}

// WithMaxNodes sets the MaxNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNodes field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithMaxNodes(value int) *FabricL3NetworkApplyConfiguration {
	b.MaxNodes = &value
	return b
}

// WithEncap sets the Encap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encap field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithEncap(value int) *FabricL3NetworkApplyConfiguration {
	b.Encap = &value
	return b
}

// WithSviType sets the SviType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SviType field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithSviType(value acifabricattachmentv1.FabricSviType) *FabricL3NetworkApplyConfiguration {
	b.SviType = &value
	return b
}

// WithPrimarySubnet sets the PrimarySubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimarySubnet field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithPrimarySubnet(value string) *FabricL3NetworkApplyConfiguration {
	b.PrimarySubnet = &value
	return b
}

// WithBGPPeerPolicy sets the BGPPeerPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGPPeerPolicy field is set to the value of the last call.
func (b *FabricL3NetworkApplyConfiguration) WithBGPPeerPolicy(value *BGPPeerPolicyApplyConfiguration) *FabricL3NetworkApplyConfiguration {
	b.BGPPeerPolicy = value
	return b
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *FabricL3NetworkApplyConfiguration) WithSubnets(values ...*FabricL3SubnetApplyConfiguration) *FabricL3NetworkApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubnets")
		}
		b.Subnets = append(b.Subnets, *values[i])
	}
	return b
}
