/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FabricVrfConfigurationApplyConfiguration represents an declarative configuration of the FabricVrfConfiguration type for use
// with apply.
type FabricVrfConfigurationApplyConfiguration struct {
	Vrf                       *VRFApplyConfiguration                        `json:"vrf,omitempty"`
	DirectlyConnectedNetworks []ConnectedL3NetworkApplyConfiguration        `json:"directlyConnectedNetworks,omitempty"`
	Tenants                   []FabricTenantConfigurationApplyConfiguration `json:"tenants,omitempty"`
}

// FabricVrfConfigurationApplyConfiguration constructs an declarative configuration of the FabricVrfConfiguration type for use with
// apply.
func FabricVrfConfiguration() *FabricVrfConfigurationApplyConfiguration {
	return &FabricVrfConfigurationApplyConfiguration{}
}

// WithVrf sets the Vrf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vrf field is set to the value of the last call.
func (b *FabricVrfConfigurationApplyConfiguration) WithVrf(value *VRFApplyConfiguration) *FabricVrfConfigurationApplyConfiguration {
	b.Vrf = value
	return b
}

// WithDirectlyConnectedNetworks adds the given value to the DirectlyConnectedNetworks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DirectlyConnectedNetworks field.
func (b *FabricVrfConfigurationApplyConfiguration) WithDirectlyConnectedNetworks(values ...*ConnectedL3NetworkApplyConfiguration) *FabricVrfConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDirectlyConnectedNetworks")
		}
		b.DirectlyConnectedNetworks = append(b.DirectlyConnectedNetworks, *values[i])
	}
	return b
}

// WithTenants adds the given value to the Tenants field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tenants field.
func (b *FabricVrfConfigurationApplyConfiguration) WithTenants(values ...*FabricTenantConfigurationApplyConfiguration) *FabricVrfConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTenants")
		}
		b.Tenants = append(b.Tenants, *values[i])
	}
	return b
}
