/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FabricTenantConfigurationStatusApplyConfiguration represents an declarative configuration of the FabricTenantConfigurationStatus type for use
// with apply.
type FabricTenantConfigurationStatusApplyConfiguration struct {
	CommonTenant          *bool                                         `json:"commonTenant,omitempty"`
	L3OutInstances        []FabricL3OutStatusApplyConfiguration         `json:"l3OutInstances,omitempty"`
	BGPPeerPrefixPolicies []BGPPeerPrefixPolicyStatusApplyConfiguration `json:"bgpInstances,omitempty"`
	Status                *string                                       `json:"status,omitempty"`
}

// FabricTenantConfigurationStatusApplyConfiguration constructs an declarative configuration of the FabricTenantConfigurationStatus type for use with
// apply.
func FabricTenantConfigurationStatus() *FabricTenantConfigurationStatusApplyConfiguration {
	return &FabricTenantConfigurationStatusApplyConfiguration{}
}

// WithCommonTenant sets the CommonTenant field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonTenant field is set to the value of the last call.
func (b *FabricTenantConfigurationStatusApplyConfiguration) WithCommonTenant(value bool) *FabricTenantConfigurationStatusApplyConfiguration {
	b.CommonTenant = &value
	return b
}

// WithL3OutInstances adds the given value to the L3OutInstances field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the L3OutInstances field.
func (b *FabricTenantConfigurationStatusApplyConfiguration) WithL3OutInstances(values ...*FabricL3OutStatusApplyConfiguration) *FabricTenantConfigurationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithL3OutInstances")
		}
		b.L3OutInstances = append(b.L3OutInstances, *values[i])
	}
	return b
}

// WithBGPPeerPrefixPolicies adds the given value to the BGPPeerPrefixPolicies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BGPPeerPrefixPolicies field.
func (b *FabricTenantConfigurationStatusApplyConfiguration) WithBGPPeerPrefixPolicies(values ...*BGPPeerPrefixPolicyStatusApplyConfiguration) *FabricTenantConfigurationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBGPPeerPrefixPolicies")
		}
		b.BGPPeerPrefixPolicies = append(b.BGPPeerPrefixPolicies, *values[i])
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *FabricTenantConfigurationStatusApplyConfiguration) WithStatus(value string) *FabricTenantConfigurationStatusApplyConfiguration {
	b.Status = &value
	return b
}
