/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PolicyPrefixApplyConfiguration represents an declarative configuration of the PolicyPrefix type for use
// with apply.
type PolicyPrefixApplyConfiguration struct {
	Subnet    *string `json:"subnet,omitempty"`
	Scope     *string `json:"scope,omitempty"`
	Aggregate *string `json:"aggregate,omitempty"`
}

// PolicyPrefixApplyConfiguration constructs an declarative configuration of the PolicyPrefix type for use with
// apply.
func PolicyPrefix() *PolicyPrefixApplyConfiguration {
	return &PolicyPrefixApplyConfiguration{}
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *PolicyPrefixApplyConfiguration) WithSubnet(value string) *PolicyPrefixApplyConfiguration {
	b.Subnet = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PolicyPrefixApplyConfiguration) WithScope(value string) *PolicyPrefixApplyConfiguration {
	b.Scope = &value
	return b
}

// WithAggregate sets the Aggregate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggregate field is set to the value of the last call.
func (b *PolicyPrefixApplyConfiguration) WithAggregate(value string) *PolicyPrefixApplyConfiguration {
	b.Aggregate = &value
	return b
}
