/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/noironetworks/aci-containers/pkg/hpp/apis/aci.hpp/v1"
	acihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/applyconfiguration/aci.hpp/v1"
	typedacihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/clientset/versioned/typed/aci.hpp/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHostprotRemoteIpContainers implements HostprotRemoteIpContainerInterface
type fakeHostprotRemoteIpContainers struct {
	*gentype.FakeClientWithListAndApply[*v1.HostprotRemoteIpContainer, *v1.HostprotRemoteIpContainerList, *acihppv1.HostprotRemoteIpContainerApplyConfiguration]
	Fake *FakeAciV1
}

func newFakeHostprotRemoteIpContainers(fake *FakeAciV1, namespace string) typedacihppv1.HostprotRemoteIpContainerInterface {
	return &fakeHostprotRemoteIpContainers{
		gentype.NewFakeClientWithListAndApply[*v1.HostprotRemoteIpContainer, *v1.HostprotRemoteIpContainerList, *acihppv1.HostprotRemoteIpContainerApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("hostprotremoteipcontainers"),
			v1.SchemeGroupVersion.WithKind("HostprotRemoteIpContainer"),
			func() *v1.HostprotRemoteIpContainer { return &v1.HostprotRemoteIpContainer{} },
			func() *v1.HostprotRemoteIpContainerList { return &v1.HostprotRemoteIpContainerList{} },
			func(dst, src *v1.HostprotRemoteIpContainerList) { dst.ListMeta = src.ListMeta },
			func(list *v1.HostprotRemoteIpContainerList) []*v1.HostprotRemoteIpContainer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.HostprotRemoteIpContainerList, items []*v1.HostprotRemoteIpContainer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
