//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotFilter) DeepCopyInto(out *HostprotFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotFilter.
func (in *HostprotFilter) DeepCopy() *HostprotFilter {
	if in == nil {
		return nil
	}
	out := new(HostprotFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotFilterContainer) DeepCopyInto(out *HostprotFilterContainer) {
	*out = *in
	if in.HostprotFilter != nil {
		in, out := &in.HostprotFilter, &out.HostprotFilter
		*out = make([]HostprotFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotFilterContainer.
func (in *HostprotFilterContainer) DeepCopy() *HostprotFilterContainer {
	if in == nil {
		return nil
	}
	out := new(HostprotFilterContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotPol) DeepCopyInto(out *HostprotPol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotPol.
func (in *HostprotPol) DeepCopy() *HostprotPol {
	if in == nil {
		return nil
	}
	out := new(HostprotPol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostprotPol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotPolList) DeepCopyInto(out *HostprotPolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostprotPol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotPolList.
func (in *HostprotPolList) DeepCopy() *HostprotPolList {
	if in == nil {
		return nil
	}
	out := new(HostprotPolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostprotPolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotPolSpec) DeepCopyInto(out *HostprotPolSpec) {
	*out = *in
	if in.HostprotSubj != nil {
		in, out := &in.HostprotSubj, &out.HostprotSubj
		*out = make([]HostprotSubj, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkPolicies != nil {
		in, out := &in.NetworkPolicies, &out.NetworkPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotPolSpec.
func (in *HostprotPolSpec) DeepCopy() *HostprotPolSpec {
	if in == nil {
		return nil
	}
	out := new(HostprotPolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotRemoteIp) DeepCopyInto(out *HostprotRemoteIp) {
	*out = *in
	if in.HppEpLabel != nil {
		in, out := &in.HppEpLabel, &out.HppEpLabel
		*out = make([]HppEpLabel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotRemoteIp.
func (in *HostprotRemoteIp) DeepCopy() *HostprotRemoteIp {
	if in == nil {
		return nil
	}
	out := new(HostprotRemoteIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotRemoteIpContainer) DeepCopyInto(out *HostprotRemoteIpContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotRemoteIpContainer.
func (in *HostprotRemoteIpContainer) DeepCopy() *HostprotRemoteIpContainer {
	if in == nil {
		return nil
	}
	out := new(HostprotRemoteIpContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostprotRemoteIpContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotRemoteIpContainerList) DeepCopyInto(out *HostprotRemoteIpContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostprotRemoteIpContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotRemoteIpContainerList.
func (in *HostprotRemoteIpContainerList) DeepCopy() *HostprotRemoteIpContainerList {
	if in == nil {
		return nil
	}
	out := new(HostprotRemoteIpContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostprotRemoteIpContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotRemoteIpContainerSpec) DeepCopyInto(out *HostprotRemoteIpContainerSpec) {
	*out = *in
	if in.HostprotRemoteIp != nil {
		in, out := &in.HostprotRemoteIp, &out.HostprotRemoteIp
		*out = make([]HostprotRemoteIp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotRemoteIpContainerSpec.
func (in *HostprotRemoteIpContainerSpec) DeepCopy() *HostprotRemoteIpContainerSpec {
	if in == nil {
		return nil
	}
	out := new(HostprotRemoteIpContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotRule) DeepCopyInto(out *HostprotRule) {
	*out = *in
	if in.RsRemoteIpContainer != nil {
		in, out := &in.RsRemoteIpContainer, &out.RsRemoteIpContainer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.HostprotFilterContainer.DeepCopyInto(&out.HostprotFilterContainer)
	if in.HostprotServiceRemoteIps != nil {
		in, out := &in.HostprotServiceRemoteIps, &out.HostprotServiceRemoteIps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotRule.
func (in *HostprotRule) DeepCopy() *HostprotRule {
	if in == nil {
		return nil
	}
	out := new(HostprotRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostprotSubj) DeepCopyInto(out *HostprotSubj) {
	*out = *in
	if in.HostprotRule != nil {
		in, out := &in.HostprotRule, &out.HostprotRule
		*out = make([]HostprotRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostprotSubj.
func (in *HostprotSubj) DeepCopy() *HostprotSubj {
	if in == nil {
		return nil
	}
	out := new(HostprotSubj)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HppEpLabel) DeepCopyInto(out *HppEpLabel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HppEpLabel.
func (in *HppEpLabel) DeepCopy() *HppEpLabel {
	if in == nil {
		return nil
	}
	out := new(HppEpLabel)
	in.DeepCopyInto(out)
	return out
}
