// +build !ignore_autogenerated

/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccProvisionSpec) DeepCopyInto(out *AccProvisionSpec) {
	*out = *in
	out.AciConfig = in.AciConfig
	out.NetConfig = in.NetConfig
	out.Registry = in.Registry
	out.Logging = in.Logging
	out.IstioConfig = in.IstioConfig
	out.DropLogConfig = in.DropLogConfig
	out.Multus = in.Multus
	out.KubeConfig = in.KubeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccProvisionSpec.
func (in *AccProvisionSpec) DeepCopy() *AccProvisionSpec {
	if in == nil {
		return nil
	}
	out := new(AccProvisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AciConfigSpec) DeepCopyInto(out *AciConfigSpec) {
	*out = *in
	out.SyncLogin = in.SyncLogin
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AciConfigSpec.
func (in *AciConfigSpec) DeepCopy() *AciConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AciConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AciContainersOperator) DeepCopyInto(out *AciContainersOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AciContainersOperator.
func (in *AciContainersOperator) DeepCopy() *AciContainersOperator {
	if in == nil {
		return nil
	}
	out := new(AciContainersOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AciContainersOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AciContainersOperatorList) DeepCopyInto(out *AciContainersOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AciContainersOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AciContainersOperatorList.
func (in *AciContainersOperatorList) DeepCopy() *AciContainersOperatorList {
	if in == nil {
		return nil
	}
	out := new(AciContainersOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AciContainersOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AciContainersOperatorSpec) DeepCopyInto(out *AciContainersOperatorSpec) {
	*out = *in
	out.AccProvisionInput = in.AccProvisionInput
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AciContainersOperatorSpec.
func (in *AciContainersOperatorSpec) DeepCopy() *AciContainersOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(AciContainersOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AciContainersOperatorStatus) DeepCopyInto(out *AciContainersOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AciContainersOperatorStatus.
func (in *AciContainersOperatorStatus) DeepCopy() *AciContainersOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(AciContainersOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DropLogConfigSpec) DeepCopyInto(out *DropLogConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DropLogConfigSpec.
func (in *DropLogConfigSpec) DeepCopy() *DropLogConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DropLogConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioConfigSpec) DeepCopyInto(out *IstioConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioConfigSpec.
func (in *IstioConfigSpec) DeepCopy() *IstioConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IstioConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeConfigSpec) DeepCopyInto(out *KubeConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeConfigSpec.
func (in *KubeConfigSpec) DeepCopy() *KubeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KubeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSpec) DeepCopyInto(out *LoggingSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSpec.
func (in *LoggingSpec) DeepCopy() *LoggingSpec {
	if in == nil {
		return nil
	}
	out := new(LoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultusSpec) DeepCopyInto(out *MultusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultusSpec.
func (in *MultusSpec) DeepCopy() *MultusSpec {
	if in == nil {
		return nil
	}
	out := new(MultusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetConfigSpec) DeepCopyInto(out *NetConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetConfigSpec.
func (in *NetConfigSpec) DeepCopy() *NetConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NetConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrySpec) DeepCopyInto(out *RegistrySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrySpec.
func (in *RegistrySpec) DeepCopy() *RegistrySpec {
	if in == nil {
		return nil
	}
	out := new(RegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncLoginSpec) DeepCopyInto(out *SyncLoginSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncLoginSpec.
func (in *SyncLoginSpec) DeepCopy() *SyncLoginSpec {
	if in == nil {
		return nil
	}
	out := new(SyncLoginSpec)
	in.DeepCopyInto(out)
	return out
}
