/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/apis/aci.fabricattachment/v1"
	acifabricattachmentv1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/applyconfiguration/aci.fabricattachment/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeFabricNetworkL3Peers implements NodeFabricNetworkL3PeerInterface
type FakeNodeFabricNetworkL3Peers struct {
	Fake *FakeAciV1
}

var nodefabricnetworkl3peersResource = v1.SchemeGroupVersion.WithResource("nodefabricnetworkl3peers")

var nodefabricnetworkl3peersKind = v1.SchemeGroupVersion.WithKind("NodeFabricNetworkL3Peer")

// Get takes name of the nodeFabricNetworkL3Peer, and returns the corresponding nodeFabricNetworkL3Peer object, and an error if there is any.
func (c *FakeNodeFabricNetworkL3Peers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodefabricnetworkl3peersResource, name), &v1.NodeFabricNetworkL3Peer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeFabricNetworkL3Peer), err
}

// List takes label and field selectors, and returns the list of NodeFabricNetworkL3Peers that match those selectors.
func (c *FakeNodeFabricNetworkL3Peers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NodeFabricNetworkL3PeerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodefabricnetworkl3peersResource, nodefabricnetworkl3peersKind, opts), &v1.NodeFabricNetworkL3PeerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NodeFabricNetworkL3PeerList{ListMeta: obj.(*v1.NodeFabricNetworkL3PeerList).ListMeta}
	for _, item := range obj.(*v1.NodeFabricNetworkL3PeerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeFabricNetworkL3Peers.
func (c *FakeNodeFabricNetworkL3Peers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodefabricnetworkl3peersResource, opts))
}

// Create takes the representation of a nodeFabricNetworkL3Peer and creates it.  Returns the server's representation of the nodeFabricNetworkL3Peer, and an error, if there is any.
func (c *FakeNodeFabricNetworkL3Peers) Create(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.CreateOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodefabricnetworkl3peersResource, nodeFabricNetworkL3Peer), &v1.NodeFabricNetworkL3Peer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeFabricNetworkL3Peer), err
}

// Update takes the representation of a nodeFabricNetworkL3Peer and updates it. Returns the server's representation of the nodeFabricNetworkL3Peer, and an error, if there is any.
func (c *FakeNodeFabricNetworkL3Peers) Update(ctx context.Context, nodeFabricNetworkL3Peer *v1.NodeFabricNetworkL3Peer, opts metav1.UpdateOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodefabricnetworkl3peersResource, nodeFabricNetworkL3Peer), &v1.NodeFabricNetworkL3Peer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeFabricNetworkL3Peer), err
}

// Delete takes name of the nodeFabricNetworkL3Peer and deletes it. Returns an error if one occurs.
func (c *FakeNodeFabricNetworkL3Peers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(nodefabricnetworkl3peersResource, name, opts), &v1.NodeFabricNetworkL3Peer{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeFabricNetworkL3Peers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodefabricnetworkl3peersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NodeFabricNetworkL3PeerList{})
	return err
}

// Patch applies the patch and returns the patched nodeFabricNetworkL3Peer.
func (c *FakeNodeFabricNetworkL3Peers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeFabricNetworkL3Peer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodefabricnetworkl3peersResource, name, pt, data, subresources...), &v1.NodeFabricNetworkL3Peer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeFabricNetworkL3Peer), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeFabricNetworkL3Peer.
func (c *FakeNodeFabricNetworkL3Peers) Apply(ctx context.Context, nodeFabricNetworkL3Peer *acifabricattachmentv1.NodeFabricNetworkL3PeerApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NodeFabricNetworkL3Peer, err error) {
	if nodeFabricNetworkL3Peer == nil {
		return nil, fmt.Errorf("nodeFabricNetworkL3Peer provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeFabricNetworkL3Peer)
	if err != nil {
		return nil, err
	}
	name := nodeFabricNetworkL3Peer.Name
	if name == nil {
		return nil, fmt.Errorf("nodeFabricNetworkL3Peer.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodefabricnetworkl3peersResource, *name, types.ApplyPatchType, data), &v1.NodeFabricNetworkL3Peer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeFabricNetworkL3Peer), err
}
