/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/apis/aci.fabricattachment/v1"
	acifabricattachmentv1 "github.com/noironetworks/aci-containers/pkg/fabricattachment/applyconfiguration/aci.fabricattachment/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNadVlanMaps implements NadVlanMapInterface
type FakeNadVlanMaps struct {
	Fake *FakeAciV1
	ns   string
}

var nadvlanmapsResource = v1.SchemeGroupVersion.WithResource("nadvlanmaps")

var nadvlanmapsKind = v1.SchemeGroupVersion.WithKind("NadVlanMap")

// Get takes name of the nadVlanMap, and returns the corresponding nadVlanMap object, and an error if there is any.
func (c *FakeNadVlanMaps) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NadVlanMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nadvlanmapsResource, c.ns, name), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// List takes label and field selectors, and returns the list of NadVlanMaps that match those selectors.
func (c *FakeNadVlanMaps) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NadVlanMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nadvlanmapsResource, nadvlanmapsKind, c.ns, opts), &v1.NadVlanMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NadVlanMapList{ListMeta: obj.(*v1.NadVlanMapList).ListMeta}
	for _, item := range obj.(*v1.NadVlanMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nadVlanMaps.
func (c *FakeNadVlanMaps) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nadvlanmapsResource, c.ns, opts))

}

// Create takes the representation of a nadVlanMap and creates it.  Returns the server's representation of the nadVlanMap, and an error, if there is any.
func (c *FakeNadVlanMaps) Create(ctx context.Context, nadVlanMap *v1.NadVlanMap, opts metav1.CreateOptions) (result *v1.NadVlanMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nadvlanmapsResource, c.ns, nadVlanMap), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// Update takes the representation of a nadVlanMap and updates it. Returns the server's representation of the nadVlanMap, and an error, if there is any.
func (c *FakeNadVlanMaps) Update(ctx context.Context, nadVlanMap *v1.NadVlanMap, opts metav1.UpdateOptions) (result *v1.NadVlanMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nadvlanmapsResource, c.ns, nadVlanMap), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNadVlanMaps) UpdateStatus(ctx context.Context, nadVlanMap *v1.NadVlanMap, opts metav1.UpdateOptions) (*v1.NadVlanMap, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nadvlanmapsResource, "status", c.ns, nadVlanMap), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// Delete takes name of the nadVlanMap and deletes it. Returns an error if one occurs.
func (c *FakeNadVlanMaps) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nadvlanmapsResource, c.ns, name, opts), &v1.NadVlanMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNadVlanMaps) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nadvlanmapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NadVlanMapList{})
	return err
}

// Patch applies the patch and returns the patched nadVlanMap.
func (c *FakeNadVlanMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NadVlanMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nadvlanmapsResource, c.ns, name, pt, data, subresources...), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nadVlanMap.
func (c *FakeNadVlanMaps) Apply(ctx context.Context, nadVlanMap *acifabricattachmentv1.NadVlanMapApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NadVlanMap, err error) {
	if nadVlanMap == nil {
		return nil, fmt.Errorf("nadVlanMap provided to Apply must not be nil")
	}
	data, err := json.Marshal(nadVlanMap)
	if err != nil {
		return nil, err
	}
	name := nadVlanMap.Name
	if name == nil {
		return nil, fmt.Errorf("nadVlanMap.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nadvlanmapsResource, c.ns, *name, types.ApplyPatchType, data), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNadVlanMaps) ApplyStatus(ctx context.Context, nadVlanMap *acifabricattachmentv1.NadVlanMapApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NadVlanMap, err error) {
	if nadVlanMap == nil {
		return nil, fmt.Errorf("nadVlanMap provided to Apply must not be nil")
	}
	data, err := json.Marshal(nadVlanMap)
	if err != nil {
		return nil, err
	}
	name := nadVlanMap.Name
	if name == nil {
		return nil, fmt.Errorf("nadVlanMap.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nadvlanmapsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.NadVlanMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NadVlanMap), err
}
