/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	acisnatv1 "github.com/noironetworks/aci-containers/pkg/snatpolicy/apis/aci.snat/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnatPolicies implements SnatPolicyInterface
type FakeSnatPolicies struct {
	Fake *FakeAciV1
}

var snatpoliciesResource = schema.GroupVersionResource{Group: "aci.snat", Version: "v1", Resource: "snatpolicies"}

var snatpoliciesKind = schema.GroupVersionKind{Group: "aci.snat", Version: "v1", Kind: "SnatPolicy"}

// Get takes name of the snatPolicy, and returns the corresponding snatPolicy object, and an error if there is any.
func (c *FakeSnatPolicies) Get(name string, options v1.GetOptions) (result *acisnatv1.SnatPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(snatpoliciesResource, name), &acisnatv1.SnatPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*acisnatv1.SnatPolicy), err
}

// List takes label and field selectors, and returns the list of SnatPolicies that match those selectors.
func (c *FakeSnatPolicies) List(opts v1.ListOptions) (result *acisnatv1.SnatPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(snatpoliciesResource, snatpoliciesKind, opts), &acisnatv1.SnatPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &acisnatv1.SnatPolicyList{ListMeta: obj.(*acisnatv1.SnatPolicyList).ListMeta}
	for _, item := range obj.(*acisnatv1.SnatPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snatPolicies.
func (c *FakeSnatPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(snatpoliciesResource, opts))
}

// Create takes the representation of a snatPolicy and creates it.  Returns the server's representation of the snatPolicy, and an error, if there is any.
func (c *FakeSnatPolicies) Create(snatPolicy *acisnatv1.SnatPolicy) (result *acisnatv1.SnatPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(snatpoliciesResource, snatPolicy), &acisnatv1.SnatPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*acisnatv1.SnatPolicy), err
}

// Update takes the representation of a snatPolicy and updates it. Returns the server's representation of the snatPolicy, and an error, if there is any.
func (c *FakeSnatPolicies) Update(snatPolicy *acisnatv1.SnatPolicy) (result *acisnatv1.SnatPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(snatpoliciesResource, snatPolicy), &acisnatv1.SnatPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*acisnatv1.SnatPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSnatPolicies) UpdateStatus(snatPolicy *acisnatv1.SnatPolicy) (*acisnatv1.SnatPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(snatpoliciesResource, "status", snatPolicy), &acisnatv1.SnatPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*acisnatv1.SnatPolicy), err
}

// Delete takes name of the snatPolicy and deletes it. Returns an error if one occurs.
func (c *FakeSnatPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(snatpoliciesResource, name), &acisnatv1.SnatPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnatPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(snatpoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &acisnatv1.SnatPolicyList{})
	return err
}

// Patch applies the patch and returns the patched snatPolicy.
func (c *FakeSnatPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *acisnatv1.SnatPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(snatpoliciesResource, name, pt, data, subresources...), &acisnatv1.SnatPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*acisnatv1.SnatPolicy), err
}
