
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "0.6.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/juju/ratelimit"

[[constraint]]
  name = "github.com/natefinch/pie"
  version = "1.0.0"

[[constraint]]
  name = "github.com/socketplane/libovsdb"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tatsushid/go-fastping"

[[constraint]]
  name = "github.com/vishvananda/netlink"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.8"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.9"

[[constraint]]
  name = "code.cloudfoundry.org/cfhttp"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-iptables"
  version = "0.2.0"

[[override]]
  name = "github.com/cenkalti/hub"
  branch = "master"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"
