
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "0.6.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/juju/ratelimit"
  branch = "master"

[[constraint]]
  name = "github.com/natefinch/pie"
  version = "1.0.0"

[[constraint]]
  name = "github.com/socketplane/libovsdb"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/tatsushid/go-fastping"
  branch = "master"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.10"

[[constraint]]
  name = "code.cloudfoundry.org/bbs"
  branch = "master"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfclient"
  branch = "master"

[[constraint]]
  name = "code.cloudfoundry.org/cfhttp"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-iptables"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "code.cloudfoundry.org/clock"
  branch = "master"

[[constraint]]
  name = "code.cloudfoundry.org/locket"
  branch = "master"

[[constraint]]
  name = "github.com/yl2chen/cidranger"
  branch = "master"

[[override]]
  name = "github.com/cenkalti/hub"
  branch = "master"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/coreos/bbolt"
  source = "https://github.com/coreos/bbolt"
  revision = "48ea1b39c25fc1bab3506fbc712ecbaa842c4d2d"

[[override]]
  name = "k8s.io/apiserver"
  revision = "d955b8a826dde3566e9dc4a51493b4afc1b51a7b"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "a01914bc74d2605fef74a0248d2eec998f0bb093"
