/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	acihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/apis/aci.hpp/v1"
	applyconfigurationacihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/applyconfiguration/aci.hpp/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/hpp/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HostprotRemoteIpContainersGetter has a method to return a HostprotRemoteIpContainerInterface.
// A group's client should implement this interface.
type HostprotRemoteIpContainersGetter interface {
	HostprotRemoteIpContainers(namespace string) HostprotRemoteIpContainerInterface
}

// HostprotRemoteIpContainerInterface has methods to work with HostprotRemoteIpContainer resources.
type HostprotRemoteIpContainerInterface interface {
	Create(ctx context.Context, hostprotRemoteIpContainer *acihppv1.HostprotRemoteIpContainer, opts metav1.CreateOptions) (*acihppv1.HostprotRemoteIpContainer, error)
	Update(ctx context.Context, hostprotRemoteIpContainer *acihppv1.HostprotRemoteIpContainer, opts metav1.UpdateOptions) (*acihppv1.HostprotRemoteIpContainer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*acihppv1.HostprotRemoteIpContainer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*acihppv1.HostprotRemoteIpContainerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *acihppv1.HostprotRemoteIpContainer, err error)
	Apply(ctx context.Context, hostprotRemoteIpContainer *applyconfigurationacihppv1.HostprotRemoteIpContainerApplyConfiguration, opts metav1.ApplyOptions) (result *acihppv1.HostprotRemoteIpContainer, err error)
	HostprotRemoteIpContainerExpansion
}

// hostprotRemoteIpContainers implements HostprotRemoteIpContainerInterface
type hostprotRemoteIpContainers struct {
	*gentype.ClientWithListAndApply[*acihppv1.HostprotRemoteIpContainer, *acihppv1.HostprotRemoteIpContainerList, *applyconfigurationacihppv1.HostprotRemoteIpContainerApplyConfiguration]
}

// newHostprotRemoteIpContainers returns a HostprotRemoteIpContainers
func newHostprotRemoteIpContainers(c *AciV1Client, namespace string) *hostprotRemoteIpContainers {
	return &hostprotRemoteIpContainers{
		gentype.NewClientWithListAndApply[*acihppv1.HostprotRemoteIpContainer, *acihppv1.HostprotRemoteIpContainerList, *applyconfigurationacihppv1.HostprotRemoteIpContainerApplyConfiguration](
			"hostprotremoteipcontainers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *acihppv1.HostprotRemoteIpContainer { return &acihppv1.HostprotRemoteIpContainer{} },
			func() *acihppv1.HostprotRemoteIpContainerList { return &acihppv1.HostprotRemoteIpContainerList{} },
		),
	}
}
