/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	acihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/apis/aci.hpp/v1"
	applyconfigurationacihppv1 "github.com/noironetworks/aci-containers/pkg/hpp/applyconfiguration/aci.hpp/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/hpp/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HostprotPolsGetter has a method to return a HostprotPolInterface.
// A group's client should implement this interface.
type HostprotPolsGetter interface {
	HostprotPols(namespace string) HostprotPolInterface
}

// HostprotPolInterface has methods to work with HostprotPol resources.
type HostprotPolInterface interface {
	Create(ctx context.Context, hostprotPol *acihppv1.HostprotPol, opts metav1.CreateOptions) (*acihppv1.HostprotPol, error)
	Update(ctx context.Context, hostprotPol *acihppv1.HostprotPol, opts metav1.UpdateOptions) (*acihppv1.HostprotPol, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*acihppv1.HostprotPol, error)
	List(ctx context.Context, opts metav1.ListOptions) (*acihppv1.HostprotPolList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *acihppv1.HostprotPol, err error)
	Apply(ctx context.Context, hostprotPol *applyconfigurationacihppv1.HostprotPolApplyConfiguration, opts metav1.ApplyOptions) (result *acihppv1.HostprotPol, err error)
	HostprotPolExpansion
}

// hostprotPols implements HostprotPolInterface
type hostprotPols struct {
	*gentype.ClientWithListAndApply[*acihppv1.HostprotPol, *acihppv1.HostprotPolList, *applyconfigurationacihppv1.HostprotPolApplyConfiguration]
}

// newHostprotPols returns a HostprotPols
func newHostprotPols(c *AciV1Client, namespace string) *hostprotPols {
	return &hostprotPols{
		gentype.NewClientWithListAndApply[*acihppv1.HostprotPol, *acihppv1.HostprotPolList, *applyconfigurationacihppv1.HostprotPolApplyConfiguration](
			"hostprotpols",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *acihppv1.HostprotPol { return &acihppv1.HostprotPol{} },
			func() *acihppv1.HostprotPolList { return &acihppv1.HostprotPolList{} },
		),
	}
}
