apiVersion: aci.erspan/v1alpha
kind: ErspanPolicy
metadata:
  name: erspan-policy
  namespace: default
spec:
  selector:
    labels:
      app: consul
    namespace: default
  source:
    adminState: "start"
    direction: "both"
  destination:
    destIP: "1.1.1.1"
    flowID: 1
