/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha "github.com/noironetworks/aci-containers/pkg/erspanpolicy/apis/aci.erspan/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeErspanPolicies implements ErspanPolicyInterface
type FakeErspanPolicies struct {
	Fake *FakeAciV1alpha
}

var erspanpoliciesResource = schema.GroupVersionResource{Group: "aci.erspan", Version: "v1alpha", Resource: "erspanpolicies"}

var erspanpoliciesKind = schema.GroupVersionKind{Group: "aci.erspan", Version: "v1alpha", Kind: "ErspanPolicy"}

// Get takes name of the erspanPolicy, and returns the corresponding erspanPolicy object, and an error if there is any.
func (c *FakeErspanPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.ErspanPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(erspanpoliciesResource, name), &v1alpha.ErspanPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ErspanPolicy), err
}

// List takes label and field selectors, and returns the list of ErspanPolicies that match those selectors.
func (c *FakeErspanPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.ErspanPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(erspanpoliciesResource, erspanpoliciesKind, opts), &v1alpha.ErspanPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.ErspanPolicyList{ListMeta: obj.(*v1alpha.ErspanPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha.ErspanPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested erspanPolicies.
func (c *FakeErspanPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(erspanpoliciesResource, opts))
}

// Create takes the representation of a erspanPolicy and creates it.  Returns the server's representation of the erspanPolicy, and an error, if there is any.
func (c *FakeErspanPolicies) Create(ctx context.Context, erspanPolicy *v1alpha.ErspanPolicy, opts v1.CreateOptions) (result *v1alpha.ErspanPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(erspanpoliciesResource, erspanPolicy), &v1alpha.ErspanPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ErspanPolicy), err
}

// Update takes the representation of a erspanPolicy and updates it. Returns the server's representation of the erspanPolicy, and an error, if there is any.
func (c *FakeErspanPolicies) Update(ctx context.Context, erspanPolicy *v1alpha.ErspanPolicy, opts v1.UpdateOptions) (result *v1alpha.ErspanPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(erspanpoliciesResource, erspanPolicy), &v1alpha.ErspanPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ErspanPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeErspanPolicies) UpdateStatus(ctx context.Context, erspanPolicy *v1alpha.ErspanPolicy, opts v1.UpdateOptions) (*v1alpha.ErspanPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(erspanpoliciesResource, "status", erspanPolicy), &v1alpha.ErspanPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ErspanPolicy), err
}

// Delete takes name of the erspanPolicy and deletes it. Returns an error if one occurs.
func (c *FakeErspanPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(erspanpoliciesResource, name), &v1alpha.ErspanPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeErspanPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(erspanpoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha.ErspanPolicyList{})
	return err
}

// Patch applies the patch and returns the patched erspanPolicy.
func (c *FakeErspanPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.ErspanPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(erspanpoliciesResource, name, pt, data, subresources...), &v1alpha.ErspanPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ErspanPolicy), err
}
