/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/noironetworks/aci-containers/pkg/nodeinfo/apis/aci.snat/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/nodeinfo/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeInfosGetter has a method to return a NodeInfoInterface.
// A group's client should implement this interface.
type NodeInfosGetter interface {
	NodeInfos(namespace string) NodeInfoInterface
}

// NodeInfoInterface has methods to work with NodeInfo resources.
type NodeInfoInterface interface {
	Create(*v1.NodeInfo) (*v1.NodeInfo, error)
	Update(*v1.NodeInfo) (*v1.NodeInfo, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeInfo, error)
	List(opts metav1.ListOptions) (*v1.NodeInfoList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeInfo, err error)
	NodeInfoExpansion
}

// nodeInfos implements NodeInfoInterface
type nodeInfos struct {
	client rest.Interface
	ns     string
}

// newNodeInfos returns a NodeInfos
func newNodeInfos(c *AciV1Client, namespace string) *nodeInfos {
	return &nodeInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeInfo, and returns the corresponding nodeInfo object, and an error if there is any.
func (c *nodeInfos) Get(name string, options metav1.GetOptions) (result *v1.NodeInfo, err error) {
	result = &v1.NodeInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeInfos that match those selectors.
func (c *nodeInfos) List(opts metav1.ListOptions) (result *v1.NodeInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeInfos.
func (c *nodeInfos) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodeinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodeInfo and creates it.  Returns the server's representation of the nodeInfo, and an error, if there is any.
func (c *nodeInfos) Create(nodeInfo *v1.NodeInfo) (result *v1.NodeInfo, err error) {
	result = &v1.NodeInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodeinfos").
		Body(nodeInfo).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeInfo and updates it. Returns the server's representation of the nodeInfo, and an error, if there is any.
func (c *nodeInfos) Update(nodeInfo *v1.NodeInfo) (result *v1.NodeInfo, err error) {
	result = &v1.NodeInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeinfos").
		Name(nodeInfo.Name).
		Body(nodeInfo).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeInfo and deletes it. Returns an error if one occurs.
func (c *nodeInfos) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeinfos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeInfos) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeinfos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeInfo.
func (c *nodeInfos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeInfo, err error) {
	result = &v1.NodeInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodeinfos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
