/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/noironetworks/aci-containers/pkg/oobpolicy/apis/aci.oob/v1"
	acioobv1 "github.com/noironetworks/aci-containers/pkg/oobpolicy/applyconfiguration/aci.oob/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOutOfBandPolicies implements OutOfBandPolicyInterface
type FakeOutOfBandPolicies struct {
	Fake *FakeAciV1
	ns   string
}

var outofbandpoliciesResource = v1.SchemeGroupVersion.WithResource("outofbandpolicies")

var outofbandpoliciesKind = v1.SchemeGroupVersion.WithKind("OutOfBandPolicy")

// Get takes name of the outOfBandPolicy, and returns the corresponding outOfBandPolicy object, and an error if there is any.
func (c *FakeOutOfBandPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.OutOfBandPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(outofbandpoliciesResource, c.ns, name), &v1.OutOfBandPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.OutOfBandPolicy), err
}

// List takes label and field selectors, and returns the list of OutOfBandPolicies that match those selectors.
func (c *FakeOutOfBandPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.OutOfBandPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(outofbandpoliciesResource, outofbandpoliciesKind, c.ns, opts), &v1.OutOfBandPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.OutOfBandPolicyList{ListMeta: obj.(*v1.OutOfBandPolicyList).ListMeta}
	for _, item := range obj.(*v1.OutOfBandPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested outOfBandPolicies.
func (c *FakeOutOfBandPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(outofbandpoliciesResource, c.ns, opts))

}

// Create takes the representation of a outOfBandPolicy and creates it.  Returns the server's representation of the outOfBandPolicy, and an error, if there is any.
func (c *FakeOutOfBandPolicies) Create(ctx context.Context, outOfBandPolicy *v1.OutOfBandPolicy, opts metav1.CreateOptions) (result *v1.OutOfBandPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(outofbandpoliciesResource, c.ns, outOfBandPolicy), &v1.OutOfBandPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.OutOfBandPolicy), err
}

// Update takes the representation of a outOfBandPolicy and updates it. Returns the server's representation of the outOfBandPolicy, and an error, if there is any.
func (c *FakeOutOfBandPolicies) Update(ctx context.Context, outOfBandPolicy *v1.OutOfBandPolicy, opts metav1.UpdateOptions) (result *v1.OutOfBandPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(outofbandpoliciesResource, c.ns, outOfBandPolicy), &v1.OutOfBandPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.OutOfBandPolicy), err
}

// Delete takes name of the outOfBandPolicy and deletes it. Returns an error if one occurs.
func (c *FakeOutOfBandPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(outofbandpoliciesResource, c.ns, name, opts), &v1.OutOfBandPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOutOfBandPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(outofbandpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.OutOfBandPolicyList{})
	return err
}

// Patch applies the patch and returns the patched outOfBandPolicy.
func (c *FakeOutOfBandPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.OutOfBandPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(outofbandpoliciesResource, c.ns, name, pt, data, subresources...), &v1.OutOfBandPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.OutOfBandPolicy), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied outOfBandPolicy.
func (c *FakeOutOfBandPolicies) Apply(ctx context.Context, outOfBandPolicy *acioobv1.OutOfBandPolicyApplyConfiguration, opts metav1.ApplyOptions) (result *v1.OutOfBandPolicy, err error) {
	if outOfBandPolicy == nil {
		return nil, fmt.Errorf("outOfBandPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(outOfBandPolicy)
	if err != nil {
		return nil, err
	}
	name := outOfBandPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("outOfBandPolicy.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(outofbandpoliciesResource, c.ns, *name, types.ApplyPatchType, data), &v1.OutOfBandPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.OutOfBandPolicy), err
}
