FROM alpine:3.10.2
RUN apk upgrade --no-cache
RUN apk update && apk add curl git
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.6/bin/linux/amd64/kubectl
RUN chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl
COPY dist-static/aci-containers-operator /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/aci-containers-operator"]
