ARG basetag=latest
ARG baserepo=quay.io/noirolabs
FROM ${baserepo}/aci-containers-base:${basetag}
RUN yum install -y --enablerepo=openstack-15-for-rhel-8-x86_64-rpms \
  --enablerepo=fast-datapath-for-rhel-8-x86_64-rpms libstdc++ libuv \
  boost-program-options boost-system boost-date-time boost-filesystem \
  boost-iostreams libnetfilter_conntrack openssl net-tools procps-ng ca-certificates \
  && yum clean all
# Required OpenShift Labels
LABEL name="ACI CNI Opflex" \
vendor="Cisco" \
version="v1.0.0" \
release="1" \
summary="This is an ACI CNI Opflex." \
description="This will deploy a single instance of ACI CNI Opflex."
# Required Licenses
COPY licenses /licenses
COPY bin/opflex_agent /usr/local/bin/
COPY bin/mcast_daemon /usr/local/bin/
COPY bin/gbp_inspect /usr/local/bin/
COPY bin/opflex_server /usr/local/bin/
COPY bin/launch-opflexagent.sh /usr/local/bin/
COPY bin/launch-mcastdaemon.sh /usr/local/bin/
COPY bin/launch-opflexserver.sh /usr/local/bin/
COPY agent/lib/ /usr/local/lib/
COPY server/lib/ /usr/local/lib/
ENV SSL_MODE="encrypted"
ENV REBOOT_WITH_OVS="true"
CMD ["/usr/local/bin/launch-opflexagent.sh"]
