FROM registry.access.redhat.com/ubi8/ubi:latest
RUN yum --disablerepo=\*ubi\* update -y && \
  yum --disablerepo=\*ubi\* install -y curl git \
  && yum clean all
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.6/bin/linux/amd64/kubectl
RUN chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl
COPY dist-static/aci-containers-operator /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/aci-containers-operator"]
