FROM noiro/opflex-build-base
WORKDIR /opflex
COPY libopflex /opflex/libopflex
ARG make_args=-j4
RUN cd /opflex/libopflex \
  && ./autogen.sh && ./configure --disable-assert --disable-shared \
  && make $make_args && make install
COPY genie /opflex/genie
RUN cd /opflex/genie/target/libmodelgbp \
  && sh autogen.sh && ./configure --disable-shared \
  && make $make_args && make install
COPY agent-ovs /opflex/agent-ovs
RUN cd /opflex/agent-ovs \
  && ./autogen.sh && ./configure --disable-shared \
  && make $make_args && make install
RUN cd /usr/local/bin \
  && for p in agent_ovs gbp_inspect mcast_daemon; do \
       objcopy --only-keep-debug "$p" "$p.debug"; \
       objcopy --strip-debug "$p"; \
       objcopy --add-gnu-debuglink="$p.debug" "$p"; \
     done
