FROM golang
ARG proxy
ENV https_proxy=$proxy
ENV http_proxy=$proxy
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
RUN apt-get update
RUN apt-get install -y python3 python3-pip && pip3 install -U pytest
RUN pip3 install -U kubernetes
ENV https_proxy=
ENV http_proxy=
