FROM noirolabs/ubibase:latest
# Istio support is disabled due to security vulnerabilities detected in
# istio.io/istio package.  The controller Go code that consumed kubectl and
# istioctl is build-excluded / commented out.
#RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
#RUN chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl
#RUN curl -sL "https://github.com/istio/istio/releases/download/1.6.5/istioctl-1.6.5-linux-amd64.tar.gz" | tar xz
#RUN chmod u+x istioctl && mv istioctl /usr/local/bin/istioctl
# Directory was used to stage upstream-istio-cr.yaml for kubectl apply in
# pkg/controller/aci_istio.go (now disabled).
#RUN mkdir -p /usr/local/var/lib/aci-cni
#COPY pkg/istiocrd/upstream-istio-cr.yaml /usr/local/var/lib/aci-cni/upstream-istio-ctrlplane-resource.yaml
COPY dist-static/aci-containers-controller /usr/local/bin/
ENTRYPOINT exec /usr/local/bin/aci-containers-controller -config-path /usr/local/etc/aci-containers/controller.conf
