FROM registry.access.redhat.com/ubi8/ubi:latest
COPY dist-static/gbpserver /usr/local/bin/

ENV GBP_SERVER_CONF=None
ENTRYPOINT exec /usr/local/bin/gbpserver -proxy-listen-port 443 --config-path $GBP_SERVER_CONF
