FROM noiro/opflex-build-base
ARG BUILDOPTS="--enable-grpc"
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/share/pkgconfig
WORKDIR /opflex
COPY opflex.tgz /opflex/opflex.tgz
ARG make_args=-j4
RUN cd /opflex && tar xvfz opflex.tgz && cd /opflex/opflex/libopflex \
  && ./autogen.sh && ./configure --disable-assert \
  && make $make_args && make install && make clean \
  && cd /opflex/opflex/genie/target/libmodelgbp \
  && sh autogen.sh && ./configure --disable-static \
  && make $make_args && make install && make clean \
  && cd /opflex/opflex/agent-ovs \
  && export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
  && ./autogen.sh && ./configure $BUILDOPTS \
  && make $make_args && make install && make clean \
  && for p in `find /usr/local/lib/ /usr/local/bin/ -type f \(\
    -name 'opflex_agent' -o \
    -name 'gbp_inspect' -o \
    -name 'mcast_daemon' -o \
    -name 'opflex_server' -o \
    -name 'libopflex*so*' -o \
    -name 'libmodelgbp*so*' -o \
    -name 'libopenvswitch*so*' -o \
    -name 'libsflow*so*' -o \
    -name 'libprometheus-cpp-*so*' -o \
    -name 'libgrpc*so*' -o \
    -name 'libproto*so*' -o \
    -name 'libre2*so*' -o \
    -name 'libupb*so*' -o \
    -name 'libabsl*so*' -o \
    -name 'libssl*so*' -o \
    -name 'libcrypto*so*' -o \
    -name 'libaddress_sorting*so*' -o \
    -name 'libgpr*so*' -o \
    -name 'libofproto*so*' \
    \)`; do \
       objcopy --only-keep-debug "$p" "$p.debug"; \
       objcopy --strip-debug "$p"; \
       objcopy --add-gnu-debuglink="$p.debug" "$p"; \
     done
