FROM registry.access.redhat.com/ubi8/ubi:latest
RUN yum --disablerepo=\*ubi\* install -y curl git \
  && yum clean all \
  && curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.6/bin/linux/amd64/kubectl \
  && chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl
# Required OpenShift Labels
LABEL name="ACI CNI Operator" \
vendor="Cisco" \
version="v1.0.0" \
release="1" \
summary="This is an ACI CNI Operator." \
description="This operator will deploy a single instance of ACI CNI Operator."
# Required Licenses
COPY docker/licenses /licenses
COPY dist-static/aci-containers-operator /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/aci-containers-operator"]
