ARG basetag=latest
ARG baserepo=quay.io/noirolabs
FROM ${baserepo}/aci-containers-base:${basetag}
# Istio support is disabled due to security vulnerabilities detected in
# istio.io/istio package.  The controller Go code that consumed kubectl and
# istioctl is build-excluded / commented out.  Keeping these lines commented
# so the dependency can be restored easily if needed in the future.
#RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
#  && chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl \
#  && curl -sL "https://github.com/istio/istio/releases/download/1.6.5/istioctl-1.6.5-linux-amd64.tar.gz" | tar xz \
#  && chmod u+x istioctl && mv istioctl /usr/local/bin/istioctl \
# Directory was used to stage upstream-istio-cr.yaml for kubectl apply in
# pkg/controller/aci_istio.go (now disabled).
#  && mkdir -p /usr/local/var/lib/aci-cni
CMD ["/usr/bin/sh"]
