FROM alpine:3.9
RUN apk upgrade --no-cache
RUN apk add --no-cache go gdb
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin
#RUN chmod -R 777 "$GOPATH"
#RUN go get github.com/derekparker/delve/cmd/dlv

COPY dist-static/aci-containers-controller /usr/local/bin/
CMD tail -f /dev/null
#ENTRYPOINT ["/usr/local/bin/aci-containers-controller", "-config-path", "/usr/local/etc/aci-containers/controller.conf"]
