ARG basetag=latest
ARG baserepo=quay.io/noirolabs
FROM ${baserepo}/aci-containers-base:${basetag}
ARG CNI_PLUGINS_VERSION=v1.9.1
RUN yum install -y wget ca-certificates tar gzip \
  && yum clean all \
  && mkdir -p /opt/cni/bin && wget -O- https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-amd64-${CNI_PLUGINS_VERSION}.tgz | tar xz -C /opt/cni/bin
CMD ["/usr/bin/sh"]
