/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/noironetworks/aci-containers/pkg/gbpcrd/apis/aci.aw/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/gbpcrd/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EpgsGetter has a method to return a EpgInterface.
// A group's client should implement this interface.
type EpgsGetter interface {
	Epgs(namespace string) EpgInterface
}

// EpgInterface has methods to work with Epg resources.
type EpgInterface interface {
	Create(*v1.Epg) (*v1.Epg, error)
	Update(*v1.Epg) (*v1.Epg, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Epg, error)
	List(opts metav1.ListOptions) (*v1.EpgList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Epg, err error)
	EpgExpansion
}

// epgs implements EpgInterface
type epgs struct {
	client rest.Interface
	ns     string
}

// newEpgs returns a Epgs
func newEpgs(c *AciV1Client, namespace string) *epgs {
	return &epgs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the epg, and returns the corresponding epg object, and an error if there is any.
func (c *epgs) Get(name string, options metav1.GetOptions) (result *v1.Epg, err error) {
	result = &v1.Epg{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("epgs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Epgs that match those selectors.
func (c *epgs) List(opts metav1.ListOptions) (result *v1.EpgList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EpgList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("epgs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested epgs.
func (c *epgs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("epgs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a epg and creates it.  Returns the server's representation of the epg, and an error, if there is any.
func (c *epgs) Create(epg *v1.Epg) (result *v1.Epg, err error) {
	result = &v1.Epg{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("epgs").
		Body(epg).
		Do().
		Into(result)
	return
}

// Update takes the representation of a epg and updates it. Returns the server's representation of the epg, and an error, if there is any.
func (c *epgs) Update(epg *v1.Epg) (result *v1.Epg, err error) {
	result = &v1.Epg{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("epgs").
		Name(epg.Name).
		Body(epg).
		Do().
		Into(result)
	return
}

// Delete takes name of the epg and deletes it. Returns an error if one occurs.
func (c *epgs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("epgs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *epgs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("epgs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched epg.
func (c *epgs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Epg, err error) {
	result = &v1.Epg{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("epgs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
