/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/noironetworks/aci-containers/pkg/gbpcrd/apis/aci.aw/v1"
	scheme "github.com/noironetworks/aci-containers/pkg/gbpcrd/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodIFsGetter has a method to return a PodIFInterface.
// A group's client should implement this interface.
type PodIFsGetter interface {
	PodIFs(namespace string) PodIFInterface
}

// PodIFInterface has methods to work with PodIF resources.
type PodIFInterface interface {
	Create(*v1.PodIF) (*v1.PodIF, error)
	Update(*v1.PodIF) (*v1.PodIF, error)
	UpdateStatus(*v1.PodIF) (*v1.PodIF, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.PodIF, error)
	List(opts metav1.ListOptions) (*v1.PodIFList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PodIF, err error)
	PodIFExpansion
}

// podIFs implements PodIFInterface
type podIFs struct {
	client rest.Interface
	ns     string
}

// newPodIFs returns a PodIFs
func newPodIFs(c *AciV1Client, namespace string) *podIFs {
	return &podIFs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podIF, and returns the corresponding podIF object, and an error if there is any.
func (c *podIFs) Get(name string, options metav1.GetOptions) (result *v1.PodIF, err error) {
	result = &v1.PodIF{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podifs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodIFs that match those selectors.
func (c *podIFs) List(opts metav1.ListOptions) (result *v1.PodIFList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PodIFList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podifs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podIFs.
func (c *podIFs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podifs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a podIF and creates it.  Returns the server's representation of the podIF, and an error, if there is any.
func (c *podIFs) Create(podIF *v1.PodIF) (result *v1.PodIF, err error) {
	result = &v1.PodIF{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podifs").
		Body(podIF).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podIF and updates it. Returns the server's representation of the podIF, and an error, if there is any.
func (c *podIFs) Update(podIF *v1.PodIF) (result *v1.PodIF, err error) {
	result = &v1.PodIF{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podifs").
		Name(podIF.Name).
		Body(podIF).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *podIFs) UpdateStatus(podIF *v1.PodIF) (result *v1.PodIF, err error) {
	result = &v1.PodIF{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podifs").
		Name(podIF.Name).
		SubResource("status").
		Body(podIF).
		Do().
		Into(result)
	return
}

// Delete takes name of the podIF and deletes it. Returns an error if one occurs.
func (c *podIFs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podifs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podIFs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podifs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podIF.
func (c *podIFs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PodIF, err error) {
	result = &v1.PodIF{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podifs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
