/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aciawv1 "github.com/noironetworks/aci-containers/pkg/gbpcrd/apis/aci.aw/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGBPServers implements GBPServerInterface
type FakeGBPServers struct {
	Fake *FakeAciV1
	ns   string
}

var gbpserversResource = schema.GroupVersionResource{Group: "aci.aw", Version: "v1", Resource: "gbpservers"}

var gbpserversKind = schema.GroupVersionKind{Group: "aci.aw", Version: "v1", Kind: "GBPServer"}

// Get takes name of the gBPServer, and returns the corresponding gBPServer object, and an error if there is any.
func (c *FakeGBPServers) Get(name string, options v1.GetOptions) (result *aciawv1.GBPServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gbpserversResource, c.ns, name), &aciawv1.GBPServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.GBPServer), err
}

// List takes label and field selectors, and returns the list of GBPServers that match those selectors.
func (c *FakeGBPServers) List(opts v1.ListOptions) (result *aciawv1.GBPServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gbpserversResource, gbpserversKind, c.ns, opts), &aciawv1.GBPServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aciawv1.GBPServerList{ListMeta: obj.(*aciawv1.GBPServerList).ListMeta}
	for _, item := range obj.(*aciawv1.GBPServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gBPServers.
func (c *FakeGBPServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gbpserversResource, c.ns, opts))

}

// Create takes the representation of a gBPServer and creates it.  Returns the server's representation of the gBPServer, and an error, if there is any.
func (c *FakeGBPServers) Create(gBPServer *aciawv1.GBPServer) (result *aciawv1.GBPServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gbpserversResource, c.ns, gBPServer), &aciawv1.GBPServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.GBPServer), err
}

// Update takes the representation of a gBPServer and updates it. Returns the server's representation of the gBPServer, and an error, if there is any.
func (c *FakeGBPServers) Update(gBPServer *aciawv1.GBPServer) (result *aciawv1.GBPServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gbpserversResource, c.ns, gBPServer), &aciawv1.GBPServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.GBPServer), err
}

// Delete takes name of the gBPServer and deletes it. Returns an error if one occurs.
func (c *FakeGBPServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gbpserversResource, c.ns, name), &aciawv1.GBPServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGBPServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gbpserversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aciawv1.GBPServerList{})
	return err
}

// Patch applies the patch and returns the patched gBPServer.
func (c *FakeGBPServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aciawv1.GBPServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gbpserversResource, c.ns, name, pt, data, subresources...), &aciawv1.GBPServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.GBPServer), err
}
