/***
Copyright 2019 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aciawv1 "github.com/noironetworks/aci-containers/pkg/gbpcrd/apis/aci.aw/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodIFs implements PodIFInterface
type FakePodIFs struct {
	Fake *FakeAciV1
	ns   string
}

var podifsResource = schema.GroupVersionResource{Group: "aci.aw", Version: "v1", Resource: "podifs"}

var podifsKind = schema.GroupVersionKind{Group: "aci.aw", Version: "v1", Kind: "PodIF"}

// Get takes name of the podIF, and returns the corresponding podIF object, and an error if there is any.
func (c *FakePodIFs) Get(name string, options v1.GetOptions) (result *aciawv1.PodIF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podifsResource, c.ns, name), &aciawv1.PodIF{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.PodIF), err
}

// List takes label and field selectors, and returns the list of PodIFs that match those selectors.
func (c *FakePodIFs) List(opts v1.ListOptions) (result *aciawv1.PodIFList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podifsResource, podifsKind, c.ns, opts), &aciawv1.PodIFList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aciawv1.PodIFList{ListMeta: obj.(*aciawv1.PodIFList).ListMeta}
	for _, item := range obj.(*aciawv1.PodIFList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podIFs.
func (c *FakePodIFs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podifsResource, c.ns, opts))

}

// Create takes the representation of a podIF and creates it.  Returns the server's representation of the podIF, and an error, if there is any.
func (c *FakePodIFs) Create(podIF *aciawv1.PodIF) (result *aciawv1.PodIF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podifsResource, c.ns, podIF), &aciawv1.PodIF{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.PodIF), err
}

// Update takes the representation of a podIF and updates it. Returns the server's representation of the podIF, and an error, if there is any.
func (c *FakePodIFs) Update(podIF *aciawv1.PodIF) (result *aciawv1.PodIF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podifsResource, c.ns, podIF), &aciawv1.PodIF{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.PodIF), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePodIFs) UpdateStatus(podIF *aciawv1.PodIF) (*aciawv1.PodIF, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(podifsResource, "status", c.ns, podIF), &aciawv1.PodIF{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.PodIF), err
}

// Delete takes name of the podIF and deletes it. Returns an error if one occurs.
func (c *FakePodIFs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podifsResource, c.ns, name), &aciawv1.PodIF{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodIFs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podifsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aciawv1.PodIFList{})
	return err
}

// Patch applies the patch and returns the patched podIF.
func (c *FakePodIFs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aciawv1.PodIF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podifsResource, c.ns, name, pt, data, subresources...), &aciawv1.PodIF{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aciawv1.PodIF), err
}
