FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils

RUN yum --nogpgcheck update -y \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
      --enablerepo=ubi-9-codeready-builder-rpms

RUN yum --nogpgcheck install -y \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
      --enablerepo=ubi-9-codeready-builder-rpms \
  libtool pkgconf-pkg-config autoconf automake make file python3-six \
  git gcc gcc-c++ diffutils python3-devel \
  expat-devel wget which libcurl-devel libcap-devel openssl-devel \
  logrotate tcpdump strace iptables-nft net-tools \
  hostname vim-minimal iproute \
 && yum clean all

RUN yum --nogpgcheck install -y \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
      --enablerepo=ubi-9-codeready-builder-rpms \
      --repofrompath=centos-baseos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os \
      --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os \
    conntrack-tools ltrace \
 && yum clean all

RUN wget https://nlnetlabs.nl/downloads/unbound/unbound-1.17.1.tar.gz \
 && tar zxvf unbound-1.17.1.tar.gz \
 && cd unbound-1.17.1 \
 && ./configure && make && make install

RUN git clone https://github.com/openvswitch/ovs.git \
 && cd ovs \
 && git checkout remotes/origin/branch-3.1 \
 && ./boot.sh && ./configure && make && make install
CMD ["/bin/sh"]
