FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils

RUN yum --nogpgcheck update -y \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms

RUN yum install -y --nogpgcheck \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
    logrotate tcpdump strace iptables-nft net-tools \
    libcap vim-minimal hostname iproute openssl procps-ng kmod tar \
 && yum clean all

RUN yum install -y --nogpgcheck \
      --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
      --repofrompath=centos-baseos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os \
      --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os \
    conntrack-tools ltrace \
 && yum clean all
# Required OpenShift Labels
LABEL name="ACI CNI Openvswitch" \
maintainer="Vishal Lella <vlella@cisco.com>" \
vendor="Cisco" \
version="v1.1.0" \
release="1" \
summary="This is an ACI CNI Openvswitch." \
description="This will deploy a single instance of ACI CNI Openvswitch."
# Required Licenses
COPY licenses /licenses
COPY usr/local/lib /usr/local/lib
COPY usr/local/bin /usr/local/bin
COPY usr/local/sbin /usr/local/sbin
COPY usr/local/share /usr/local/share
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
CMD ["/usr/local/bin/launch-ovs.sh"]
