FROM registry.access.redhat.com/ubi8/ubi:latest
# Required OpenShift Labels
LABEL name="ACI CNI Openvswitch" \
vendor="Cisco" \
version="v1.0.0" \
release="1" \
summary="This is an ACI CNI Openvswitch." \
description="This will deploy a single instance of ACI CNI Openvswitch."
RUN yum update --disablerepo=* --enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos-rpms -y && rm -rf /var/cache/yum
RUN yum install --disablerepo=* --enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos-rpms httpd -y && rm -rf /var/cache/yum
# Required Licenses
COPY docker/licenses /licenses
#RUN yum install -y --enablerepo=openstack-15-for-rhel-8-x86_64-rpms \
RUN yum install -y \
  --enablerepo=fast-datapath-for-rhel-8-x86_64-rpms openvswitch2.13 logrotate conntrack-tools \
  tcpdump curl strace ltrace iptables net-tools && yum clean all
COPY docker/launch-ovs.sh docker/liveness-ovs.sh dist-static/ovsresync /usr/local/bin/
CMD ["/usr/local/bin/launch-ovs.sh"]
