FROM registry.access.redhat.com/ubi9/ubi:latest
# Required OpenShift Labels
LABEL name="ACI Containers Webhook" \
vendor="Cisco" \
version="v1.1.0" \
release="1" \
summary="This is a webhook for ACI containers" \
description="This will deploy a single instance of ACI containers Webhook."
RUN yum update --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum
# Required Licenses
COPY docker/licenses /licenses
COPY dist-static/aci-containers-webhook docker/launch-webhook.sh /usr/local/bin/
CMD ["/usr/local/bin/launch-webhook.sh"]
