FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os

RUN yum update --exclude=openssl* -y --nogpgcheck --disablerepo=* --repofrompath=centos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os  --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os && rm -rf /var/cache/yum

RUN yum --nogpgcheck --disablerepo=* install --repofrompath=centos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os -y \
  libtool pkgconfig autoconf automake make file python3-six \
  git gcc gcc-c++ diffutils python3-devel \
  expat-devel wget which curl-devel libcap-devel \
  logrotate conntrack-tools tcpdump strace ltrace iptables net-tools \
  hostname vi iproute \
 && yum clean all

RUN yum update --exclude=openssl* --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum

RUN yum --nogpgcheck --disablerepo=* install --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y \
  openssl-devel-3.2.2-6.el9_5.1 \
 && yum clean all

RUN wget https://nlnetlabs.nl/downloads/unbound/unbound-1.17.1.tar.gz \
 && tar zxvf unbound-1.17.1.tar.gz \
 && cd unbound-1.17.1 \
 && ./configure && make && make install

RUN git clone https://github.com/openvswitch/ovs.git \
 && cd ovs \
 && git checkout remotes/origin/branch-3.1 \
 && ./boot.sh && ./configure && make && make install
CMD ["/bin/sh"]
