FROM registry.access.redhat.com/ubi9/ubi:latest
# Required OpenShift Labels
LABEL name="ACI CNI cnideploy" \
vendor="Cisco" \
version="v1.1.0" \
release="1" \
summary="This is an ACI CNI cnideploy." \
description="This operator will deploy a single instance of ACI CNI cnideploy."
RUN yum update --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum
# Required Licenses
COPY docker/licenses /licenses
RUN yum install --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y wget ca-certificates tar gzip \
  && yum clean all \
  && mkdir -p /opt/cni/bin && wget -O- https://github.com/containernetworking/plugins/releases/download/v0.9.0/cni-plugins-linux-arm64-v0.9.0.tgz | tar xz -C /opt/cni/bin
COPY docker/launch-cnideploy.sh /usr/local/bin/
CMD ["/usr/local/bin/launch-cnideploy.sh"]