FROM alpine:3.12.3
RUN apk upgrade --no-cache && \
  apk add --no-cache wget ca-certificates && update-ca-certificates
ARG CNI_PLUGINS_VERSION=v1.9.1
RUN mkdir -p /opt/cni/bin && wget -O- https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-amd64-${CNI_PLUGINS_VERSION}.tgz | tar xz -C /opt/cni/bin
COPY launch-cnideploy.sh /usr/local/bin/
CMD ["/usr/local/bin/launch-cnideploy.sh"]
