FROM challa/opflex-build-base:master1
ARG BUILDOPTS="--enable-grpc --enable-prometheus"
WORKDIR /opflex
COPY libopflex /opflex/libopflex
ARG make_args=-j4
RUN cd /opflex/libopflex \
  && ./autogen.sh && ./configure --disable-assert \
  && make $make_args && make install && make clean
COPY genie /opflex/genie
RUN cd /opflex/genie/target/libmodelgbp \
  && sh autogen.sh && ./configure --disable-static \
  && make $make_args && make install && make clean
COPY agent-ovs /opflex/agent-ovs
RUN cd /opflex/agent-ovs \
  && ./autogen.sh && ./configure $BUILDOPTS \
  && make $make_args && make install && make clean
RUN cd /opflex/agent-ovs \
  && make -C ./bpf \
  && make -C  ./bpf install \
  && make -C  ./bpf clean
RUN for p in `find /usr/local/lib/ /usr/local/bin/ -type f \(\
    -name 'opflex_agent' -o \
    -name 'gbp_client_stress' -o \
    -name 'gbp_inspect' -o \
    -name 'mcast_daemon' -o \
    -name 'opflex_server' -o \
    -name 'map_ctrl' -o \
    -name 'libopflex*so*' -o \
    -name 'libmodelgbp*so*' -o \
    -name 'libopenvswitch*so*' -o \
    -name 'libsflow*so*' -o \
    -name 'libprometheus-cpp-*so*' -o \
    -name 'libgrpc*so*' -o \
    -name 'libproto*so*' -o \
    -name 'libre2*so*' -o \
    -name 'libupb*so*' -o \
    -name 'libabsl*so*' -o \
    -name 'libssl*so*' -o \
    -name 'libcrypto*so*' -o \
    -name 'libaddress_sorting*so*' -o \
    -name 'libgpr*so*' -o \
    -name 'libofproto*so*' \
    \)`; do \
       objcopy --only-keep-debug "$p" "$p.debug"; \
       objcopy --strip-debug "$p"; \
       objcopy --add-gnu-debuglink="$p.debug" "$p"; \
     done
