FROM alpine:3.12.3
RUN apk upgrade --no-cache
# Istio support is disabled due to security vulnerabilities detected in
# istio.io/istio package.  The controller Go code that consumed kubectl and
# istioctl is build-excluded / commented out.
#RUN apk update && apk add curl && \
#    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
#    chmod u+x kubectl && mv kubectl /usr/local/bin/kubectl && \
#    curl -LO https://istio.io/operator.yaml && \
# Directory was used to stage upstream-istio-cr.yaml for kubectl apply in
# pkg/controller/aci_istio.go (now disabled).
#    mkdir -p /usr/local/var/lib/aci-cni
#COPY pkg/istiocrd/upstream-istio-cr.yaml /usr/local/var/lib/aci-cni/upstream-istio-ctrlplane-resource.yaml
COPY dist-static/aci-containers-controller /usr/local/bin/
ENTRYPOINT exec /usr/local/bin/aci-containers-controller -config-path /usr/local/etc/aci-containers/controller.conf
