/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/noironetworks/aci-containers/pkg/oobpolicy/apis/aci.oob/v1"
)

// OutOfBandPolicySpecApplyConfiguration represents an declarative configuration of the OutOfBandPolicySpec type for use
// with apply.
type OutOfBandPolicySpecApplyConfiguration struct {
	TunnelEpAdvertisementInterval *int                              `json:"TunnelEpAdvertisementInterval,omitempty"`
	VmmEpgDeploymentImmediacy     *v1.VmmEpgDeploymentImmediacyType `json:"VmmEpgDeploymentImmediacy,omitempty"`
}

// OutOfBandPolicySpecApplyConfiguration constructs an declarative configuration of the OutOfBandPolicySpec type for use with
// apply.
func OutOfBandPolicySpec() *OutOfBandPolicySpecApplyConfiguration {
	return &OutOfBandPolicySpecApplyConfiguration{}
}

// WithTunnelEpAdvertisementInterval sets the TunnelEpAdvertisementInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TunnelEpAdvertisementInterval field is set to the value of the last call.
func (b *OutOfBandPolicySpecApplyConfiguration) WithTunnelEpAdvertisementInterval(value int) *OutOfBandPolicySpecApplyConfiguration {
	b.TunnelEpAdvertisementInterval = &value
	return b
}

// WithVmmEpgDeploymentImmediacy sets the VmmEpgDeploymentImmediacy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VmmEpgDeploymentImmediacy field is set to the value of the last call.
func (b *OutOfBandPolicySpecApplyConfiguration) WithVmmEpgDeploymentImmediacy(value v1.VmmEpgDeploymentImmediacyType) *OutOfBandPolicySpecApplyConfiguration {
	b.VmmEpgDeploymentImmediacy = &value
	return b
}
