FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils
RUN yum update -y --nogpgcheck --disablerepo=* --repofrompath=centos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os  --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os && rm -rf /var/cache/yum
RUN yum install -y --nogpgcheck --disablerepo=* --repofrompath=centos,https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os --repofrompath=centos-app,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os \
  logrotate conntrack-tools tcpdump strace ltrace iptables net-tools \
  libcap vi hostname iproute openssl procps-ng \
 && yum clean all
# Required OpenShift Labels
LABEL name="ACI CNI Openvswitch" \
vendor="Cisco" \
version="v1.1.0" \
release="1" \
summary="This is an ACI CNI Openvswitch." \
description="This will deploy a single instance of ACI CNI Openvswitch."
# Required Licenses
COPY licenses /licenses
COPY usr/local/lib /usr/local/lib
COPY usr/local/bin /usr/local/bin
COPY usr/local/sbin /usr/local/sbin
COPY usr/local/share /usr/local/share
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
CMD ["/usr/local/bin/launch-ovs.sh"]
