FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os \
 && yum --nogpgcheck -y update
RUN yum --nogpgcheck --disablerepo=* install -y \
  libstdc++ libuv \
  boost-program-options boost-system boost-date-time boost-filesystem \
  boost-iostreams libnetfilter_conntrack openssl net-tools procps-ng ca-certificates \
  && yum clean all
# Required OpenShift Labels
LABEL name="ACI CNI Opflex" \
vendor="Cisco" \
version="v1.1.0" \
release="1" \
summary="This is an ACI CNI Opflex." \
description="This will deploy a single instance of ACI CNI Opflex."
# Required Licenses
COPY bin/opflex_agent /usr/local/bin/
COPY bin/mcast_daemon /usr/local/bin/
COPY bin/gbp_inspect /usr/local/bin/
COPY bin/opflex_server /usr/local/bin/
COPY bin/launch-opflexagent.sh /usr/local/bin/
COPY bin/launch-mcastdaemon.sh /usr/local/bin/
COPY bin/launch-opflexserver.sh /usr/local/bin/
COPY agent/lib/ /usr/local/lib/
COPY usr/local/lib64 /usr/local/lib64
COPY server/lib/ /usr/local/lib/
ENV SSL_MODE="encrypted"
ENV REBOOT_WITH_OVS="true"
CMD ["/usr/local/bin/launch-opflexagent.sh"]
