FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y yum yum-utils \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os \
 && yum-config-manager --add-repo=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os \
 && yum --nogpgcheck -y update
RUN yum --nogpgcheck --disablerepo=\*ubi\* install -y libstdc++ libuv \
  boost-program-options boost-system boost-date-time boost-filesystem \
  boost-iostreams libnetfilter_conntrack openssl net-tools procps-ng ca-certificates \
  && yum clean all
COPY bin/opflex_server /usr/local/bin/
COPY bin/gbp_inspect /usr/local/bin/
COPY bin/launch-opflexserver.sh /usr/local/bin/
COPY usr/local/lib64 /usr/local/lib64
COPY server/lib/ /usr/local/lib/
CMD ["/usr/local/bin/launch-opflexserver.sh"]
