/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	acidroplogv1alpha1 "github.com/noironetworks/aci-containers/pkg/droplog/apis/aci.droplog/v1alpha1"
	versioned "github.com/noironetworks/aci-containers/pkg/droplog/clientset/versioned"
	internalinterfaces "github.com/noironetworks/aci-containers/pkg/droplog/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/noironetworks/aci-containers/pkg/droplog/listers/aci.droplog/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EnableDropLogInformer provides access to a shared informer and lister for
// EnableDropLogs.
type EnableDropLogInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EnableDropLogLister
}

type enableDropLogInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEnableDropLogInformer constructs a new informer for EnableDropLog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEnableDropLogInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEnableDropLogInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEnableDropLogInformer constructs a new informer for EnableDropLog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEnableDropLogInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AciV1alpha1().EnableDropLogs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AciV1alpha1().EnableDropLogs().Watch(context.TODO(), options)
			},
		},
		&acidroplogv1alpha1.EnableDropLog{},
		resyncPeriod,
		indexers,
	)
}

func (f *enableDropLogInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEnableDropLogInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *enableDropLogInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&acidroplogv1alpha1.EnableDropLog{}, f.defaultInformer)
}

func (f *enableDropLogInformer) Lister() v1alpha1.EnableDropLogLister {
	return v1alpha1.NewEnableDropLogLister(f.Informer().GetIndexer())
}
