/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	acidroplogv1alpha1 "github.com/noironetworks/aci-containers/pkg/droplog/apis/aci.droplog/v1alpha1"
	versioned "github.com/noironetworks/aci-containers/pkg/droplog/clientset/versioned"
	internalinterfaces "github.com/noironetworks/aci-containers/pkg/droplog/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/noironetworks/aci-containers/pkg/droplog/listers/aci.droplog/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PruneDropLogInformer provides access to a shared informer and lister for
// PruneDropLogs.
type PruneDropLogInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PruneDropLogLister
}

type pruneDropLogInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPruneDropLogInformer constructs a new informer for PruneDropLog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPruneDropLogInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPruneDropLogInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPruneDropLogInformer constructs a new informer for PruneDropLog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPruneDropLogInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AciV1alpha1().PruneDropLogs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AciV1alpha1().PruneDropLogs().Watch(context.TODO(), options)
			},
		},
		&acidroplogv1alpha1.PruneDropLog{},
		resyncPeriod,
		indexers,
	)
}

func (f *pruneDropLogInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPruneDropLogInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pruneDropLogInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&acidroplogv1alpha1.PruneDropLog{}, f.defaultInformer)
}

func (f *pruneDropLogInformer) Lister() v1alpha1.PruneDropLogLister {
	return v1alpha1.NewPruneDropLogLister(f.Informer().GetIndexer())
}
