// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: gbp.proto

package gbpserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GBPOperation_OpCode int32

const (
	GBPOperation_ADD              GBPOperation_OpCode = 0
	GBPOperation_REPLACE          GBPOperation_OpCode = 1
	GBPOperation_DELETE           GBPOperation_OpCode = 2
	GBPOperation_DELETE_RECURSIVE GBPOperation_OpCode = 3
)

// Enum value maps for GBPOperation_OpCode.
var (
	GBPOperation_OpCode_name = map[int32]string{
		0: "ADD",
		1: "REPLACE",
		2: "DELETE",
		3: "DELETE_RECURSIVE",
	}
	GBPOperation_OpCode_value = map[string]int32{
		"ADD":              0,
		"REPLACE":          1,
		"DELETE":           2,
		"DELETE_RECURSIVE": 3,
	}
)

func (x GBPOperation_OpCode) Enum() *GBPOperation_OpCode {
	p := new(GBPOperation_OpCode)
	*p = x
	return p
}

func (x GBPOperation_OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GBPOperation_OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gbp_proto_enumTypes[0].Descriptor()
}

func (GBPOperation_OpCode) Type() protoreflect.EnumType {
	return &file_gbp_proto_enumTypes[0]
}

func (x GBPOperation_OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GBPOperation_OpCode.Descriptor instead.
func (GBPOperation_OpCode) EnumDescriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{0, 0}
}

// A GBPOperation adds, replaces or deletes a subtree
type GBPOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcode     GBPOperation_OpCode `protobuf:"varint,1,opt,name=opcode,proto3,enum=gbpserver.GBPOperation_OpCode" json:"opcode,omitempty"`
	ObjectList []*GBPObject        `protobuf:"bytes,2,rep,name=object_list,json=objectList,proto3" json:"object_list,omitempty"`
}

func (x *GBPOperation) Reset() {
	*x = GBPOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GBPOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GBPOperation) ProtoMessage() {}

func (x *GBPOperation) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GBPOperation.ProtoReflect.Descriptor instead.
func (*GBPOperation) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{0}
}

func (x *GBPOperation) GetOpcode() GBPOperation_OpCode {
	if x != nil {
		return x.Opcode
	}
	return GBPOperation_ADD
}

func (x *GBPOperation) GetObjectList() []*GBPObject {
	if x != nil {
		return x.ObjectList
	}
	return nil
}

// Version is used for syncing between client and server
type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

// GBPObject is a generic definition representing an object
type GBPObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject        string      `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Uri            string      `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Properties     []*Property `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	Children       []string    `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	ParentSubject  string      `protobuf:"bytes,5,opt,name=parent_subject,json=parentSubject,proto3" json:"parent_subject,omitempty"`
	ParentUri      string      `protobuf:"bytes,6,opt,name=parent_uri,json=parentUri,proto3" json:"parent_uri,omitempty"`
	ParentRelation string      `protobuf:"bytes,7,opt,name=parent_relation,json=parentRelation,proto3" json:"parent_relation,omitempty"`
}

func (x *GBPObject) Reset() {
	*x = GBPObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GBPObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GBPObject) ProtoMessage() {}

func (x *GBPObject) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GBPObject.ProtoReflect.Descriptor instead.
func (*GBPObject) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{2}
}

func (x *GBPObject) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GBPObject) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GBPObject) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GBPObject) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *GBPObject) GetParentSubject() string {
	if x != nil {
		return x.ParentSubject
	}
	return ""
}

func (x *GBPObject) GetParentUri() string {
	if x != nil {
		return x.ParentUri
	}
	return ""
}

func (x *GBPObject) GetParentRelation() string {
	if x != nil {
		return x.ParentRelation
	}
	return ""
}

// Property is a name value pair, where the value could be one of [string, int, Reference]
type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//
	//	*Property_StrVal
	//	*Property_IntVal
	//	*Property_RefVal
	Value isProperty_Value `protobuf_oneof:"value"`
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{3}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Property) GetValue() isProperty_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Property) GetStrVal() string {
	if x, ok := x.GetValue().(*Property_StrVal); ok {
		return x.StrVal
	}
	return ""
}

func (x *Property) GetIntVal() int32 {
	if x, ok := x.GetValue().(*Property_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *Property) GetRefVal() *Reference {
	if x, ok := x.GetValue().(*Property_RefVal); ok {
		return x.RefVal
	}
	return nil
}

type isProperty_Value interface {
	isProperty_Value()
}

type Property_StrVal struct {
	StrVal string `protobuf:"bytes,2,opt,name=strVal,proto3,oneof"`
}

type Property_IntVal struct {
	IntVal int32 `protobuf:"varint,3,opt,name=intVal,proto3,oneof"`
}

type Property_RefVal struct {
	RefVal *Reference `protobuf:"bytes,4,opt,name=refVal,proto3,oneof"`
}

func (*Property_StrVal) isProperty_Value() {}

func (*Property_IntVal) isProperty_Value() {}

func (*Property_RefVal) isProperty_Value() {}

// Reference refers to another GBP object
type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject      string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ReferenceUri string `protobuf:"bytes,2,opt,name=reference_uri,json=referenceUri,proto3" json:"reference_uri,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{4}
}

func (x *Reference) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Reference) GetReferenceUri() string {
	if x != nil {
		return x.ReferenceUri
	}
	return ""
}

// VTEP is the ip address of the vtep matching a node.
type VTEP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vtep string `protobuf:"bytes,1,opt,name=vtep,proto3" json:"vtep,omitempty"`
}

func (x *VTEP) Reset() {
	*x = VTEP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VTEP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTEP) ProtoMessage() {}

func (x *VTEP) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTEP.ProtoReflect.Descriptor instead.
func (*VTEP) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{5}
}

func (x *VTEP) GetVtep() string {
	if x != nil {
		return x.Vtep
	}
	return ""
}

// VTEPList is the list of vteps, corresponding to the connected grpc clients
type VTEPList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vteps []string `protobuf:"bytes,1,rep,name=vteps,proto3" json:"vteps,omitempty"`
}

func (x *VTEPList) Reset() {
	*x = VTEPList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VTEPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTEPList) ProtoMessage() {}

func (x *VTEPList) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTEPList.ProtoReflect.Descriptor instead.
func (*VTEPList) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{6}
}

func (x *VTEPList) GetVteps() []string {
	if x != nil {
		return x.Vteps
	}
	return nil
}

// ObjectList is a list of GBP objects
type ObjectList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoList []*GBPObject `protobuf:"bytes,1,rep,name=mo_list,json=moList,proto3" json:"mo_list,omitempty"`
}

func (x *ObjectList) Reset() {
	*x = ObjectList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectList) ProtoMessage() {}

func (x *ObjectList) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectList.ProtoReflect.Descriptor instead.
func (*ObjectList) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectList) GetMoList() []*GBPObject {
	if x != nil {
		return x.MoList
	}
	return nil
}

type EmptyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gbp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_gbp_proto_rawDescGZIP(), []int{8}
}

var File_gbp_proto protoreflect.FileDescriptor

var file_gbp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x62, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x62, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xbf, 0x01, 0x0a, 0x0c, 0x47, 0x42, 0x50, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x47, 0x42, 0x50, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x35, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x42, 0x50, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x50,
	0x4c, 0x41, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43,
	0x55, 0x52, 0x53, 0x49, 0x56, 0x45, 0x10, 0x03, 0x22, 0x21, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xf7, 0x01, 0x0a, 0x09,
	0x47, 0x42, 0x50, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x33, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x62, 0x70, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x69, 0x12, 0x27, 0x0a, 0x0f,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8b, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x12, 0x18, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65,
	0x66, 0x56, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x62, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x66, 0x56, 0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x55, 0x72, 0x69, 0x22,
	0x1a, 0x0a, 0x04, 0x56, 0x54, 0x45, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x74, 0x65, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x74, 0x65, 0x70, 0x22, 0x20, 0x0a, 0x08, 0x56,
	0x54, 0x45, 0x50, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x74, 0x65, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x74, 0x65, 0x70, 0x73, 0x22, 0x3b, 0x0a,
	0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6d,
	0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x42, 0x50, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x06, 0x6d, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x32, 0xb7, 0x01, 0x0a, 0x03, 0x47, 0x42, 0x50, 0x12, 0x3e,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x12, 0x2e,
	0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x17, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x42,
	0x50, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x37,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x54, 0x45, 0x50, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x62,
	0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x1a, 0x13, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x54, 0x45,
	0x50, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6e,
	0x61, 0x70, 0x53, 0x68, 0x6f, 0x74, 0x12, 0x0f, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x56, 0x54, 0x45, 0x50, 0x1a, 0x15, 0x2e, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x67, 0x62, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gbp_proto_rawDescOnce sync.Once
	file_gbp_proto_rawDescData = file_gbp_proto_rawDesc
)

func file_gbp_proto_rawDescGZIP() []byte {
	file_gbp_proto_rawDescOnce.Do(func() {
		file_gbp_proto_rawDescData = protoimpl.X.CompressGZIP(file_gbp_proto_rawDescData)
	})
	return file_gbp_proto_rawDescData
}

var file_gbp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gbp_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gbp_proto_goTypes = []interface{}{
	(GBPOperation_OpCode)(0), // 0: gbpserver.GBPOperation.OpCode
	(*GBPOperation)(nil),     // 1: gbpserver.GBPOperation
	(*Version)(nil),          // 2: gbpserver.Version
	(*GBPObject)(nil),        // 3: gbpserver.GBPObject
	(*Property)(nil),         // 4: gbpserver.Property
	(*Reference)(nil),        // 5: gbpserver.Reference
	(*VTEP)(nil),             // 6: gbpserver.VTEP
	(*VTEPList)(nil),         // 7: gbpserver.VTEPList
	(*ObjectList)(nil),       // 8: gbpserver.ObjectList
	(*EmptyMsg)(nil),         // 9: gbpserver.EmptyMsg
}
var file_gbp_proto_depIdxs = []int32{
	0, // 0: gbpserver.GBPOperation.opcode:type_name -> gbpserver.GBPOperation.OpCode
	3, // 1: gbpserver.GBPOperation.object_list:type_name -> gbpserver.GBPObject
	4, // 2: gbpserver.GBPObject.properties:type_name -> gbpserver.Property
	5, // 3: gbpserver.Property.refVal:type_name -> gbpserver.Reference
	3, // 4: gbpserver.ObjectList.mo_list:type_name -> gbpserver.GBPObject
	2, // 5: gbpserver.GBP.ListObjects:input_type -> gbpserver.Version
	9, // 6: gbpserver.GBP.ListVTEPs:input_type -> gbpserver.EmptyMsg
	6, // 7: gbpserver.GBP.GetSnapShot:input_type -> gbpserver.VTEP
	1, // 8: gbpserver.GBP.ListObjects:output_type -> gbpserver.GBPOperation
	7, // 9: gbpserver.GBP.ListVTEPs:output_type -> gbpserver.VTEPList
	8, // 10: gbpserver.GBP.GetSnapShot:output_type -> gbpserver.ObjectList
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gbp_proto_init() }
func file_gbp_proto_init() {
	if File_gbp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gbp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GBPOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GBPObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VTEP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VTEPList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gbp_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Property_StrVal)(nil),
		(*Property_IntVal)(nil),
		(*Property_RefVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gbp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gbp_proto_goTypes,
		DependencyIndexes: file_gbp_proto_depIdxs,
		EnumInfos:         file_gbp_proto_enumTypes,
		MessageInfos:      file_gbp_proto_msgTypes,
	}.Build()
	File_gbp_proto = out.File
	file_gbp_proto_rawDesc = nil
	file_gbp_proto_goTypes = nil
	file_gbp_proto_depIdxs = nil
}
