/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/noironetworks/aci-containers/pkg/droplog/apis/aci.droplog/v1alpha1"
	scheme "github.com/noironetworks/aci-containers/pkg/droplog/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PruneDropLogsGetter has a method to return a PruneDropLogInterface.
// A group's client should implement this interface.
type PruneDropLogsGetter interface {
	PruneDropLogs() PruneDropLogInterface
}

// PruneDropLogInterface has methods to work with PruneDropLog resources.
type PruneDropLogInterface interface {
	Create(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.CreateOptions) (*v1alpha1.PruneDropLog, error)
	Update(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.UpdateOptions) (*v1alpha1.PruneDropLog, error)
	UpdateStatus(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.UpdateOptions) (*v1alpha1.PruneDropLog, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PruneDropLog, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PruneDropLogList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PruneDropLog, err error)
	PruneDropLogExpansion
}

// pruneDropLogs implements PruneDropLogInterface
type pruneDropLogs struct {
	client rest.Interface
}

// newPruneDropLogs returns a PruneDropLogs
func newPruneDropLogs(c *AciV1alpha1Client) *pruneDropLogs {
	return &pruneDropLogs{
		client: c.RESTClient(),
	}
}

// Get takes name of the pruneDropLog, and returns the corresponding pruneDropLog object, and an error if there is any.
func (c *pruneDropLogs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PruneDropLog, err error) {
	result = &v1alpha1.PruneDropLog{}
	err = c.client.Get().
		Resource("prunedroplogs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PruneDropLogs that match those selectors.
func (c *pruneDropLogs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PruneDropLogList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PruneDropLogList{}
	err = c.client.Get().
		Resource("prunedroplogs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pruneDropLogs.
func (c *pruneDropLogs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("prunedroplogs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pruneDropLog and creates it.  Returns the server's representation of the pruneDropLog, and an error, if there is any.
func (c *pruneDropLogs) Create(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.CreateOptions) (result *v1alpha1.PruneDropLog, err error) {
	result = &v1alpha1.PruneDropLog{}
	err = c.client.Post().
		Resource("prunedroplogs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pruneDropLog).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pruneDropLog and updates it. Returns the server's representation of the pruneDropLog, and an error, if there is any.
func (c *pruneDropLogs) Update(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.UpdateOptions) (result *v1alpha1.PruneDropLog, err error) {
	result = &v1alpha1.PruneDropLog{}
	err = c.client.Put().
		Resource("prunedroplogs").
		Name(pruneDropLog.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pruneDropLog).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pruneDropLogs) UpdateStatus(ctx context.Context, pruneDropLog *v1alpha1.PruneDropLog, opts v1.UpdateOptions) (result *v1alpha1.PruneDropLog, err error) {
	result = &v1alpha1.PruneDropLog{}
	err = c.client.Put().
		Resource("prunedroplogs").
		Name(pruneDropLog.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pruneDropLog).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pruneDropLog and deletes it. Returns an error if one occurs.
func (c *pruneDropLogs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("prunedroplogs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pruneDropLogs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("prunedroplogs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pruneDropLog.
func (c *pruneDropLogs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PruneDropLog, err error) {
	result = &v1alpha1.PruneDropLog{}
	err = c.client.Patch(pt).
		Resource("prunedroplogs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
