/***
Copyright 2021 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/noironetworks/aci-containers/pkg/gbpcrd/apis/acipolicy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContracts implements ContractInterface
type FakeContracts struct {
	Fake *FakeAciV1
	ns   string
}

var contractsResource = v1.SchemeGroupVersion.WithResource("contracts")

var contractsKind = v1.SchemeGroupVersion.WithKind("Contract")

// Get takes name of the contract, and returns the corresponding contract object, and an error if there is any.
func (c *FakeContracts) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Contract, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(contractsResource, c.ns, name), &v1.Contract{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Contract), err
}

// List takes label and field selectors, and returns the list of Contracts that match those selectors.
func (c *FakeContracts) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ContractList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(contractsResource, contractsKind, c.ns, opts), &v1.ContractList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ContractList{ListMeta: obj.(*v1.ContractList).ListMeta}
	for _, item := range obj.(*v1.ContractList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested contracts.
func (c *FakeContracts) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(contractsResource, c.ns, opts))

}

// Create takes the representation of a contract and creates it.  Returns the server's representation of the contract, and an error, if there is any.
func (c *FakeContracts) Create(ctx context.Context, contract *v1.Contract, opts metav1.CreateOptions) (result *v1.Contract, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(contractsResource, c.ns, contract), &v1.Contract{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Contract), err
}

// Update takes the representation of a contract and updates it. Returns the server's representation of the contract, and an error, if there is any.
func (c *FakeContracts) Update(ctx context.Context, contract *v1.Contract, opts metav1.UpdateOptions) (result *v1.Contract, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(contractsResource, c.ns, contract), &v1.Contract{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Contract), err
}

// Delete takes name of the contract and deletes it. Returns an error if one occurs.
func (c *FakeContracts) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(contractsResource, c.ns, name, opts), &v1.Contract{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContracts) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(contractsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ContractList{})
	return err
}

// Patch applies the patch and returns the patched contract.
func (c *FakeContracts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Contract, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(contractsResource, c.ns, name, pt, data, subresources...), &v1.Contract{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Contract), err
}
