apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    aci-containers-config-version: 1347910f-26f6-409f-8da4-e89a76a037fd
    name: aci-containers-operator
    network-plugin: aci-containers
  name: aci-containers-operator
  namespace: aci-containers-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: aci-containers-operator
      network-plugin: aci-containers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        name: aci-containers-operator
        network-plugin: aci-containers
      name: aci-containers-operator
      namespace: aci-containers-system
    spec:
      containers:
      - image: docker.io/abhi21/aci-containers-operator:latest
        imagePullPolicy: Always
        name: aci-containers-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.kube/config
          name: host
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aci-containers-operator
      serviceAccountName: aci-containers-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/kubeconfig
          type: ""
        name: host

