apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: nodeinfos.aci.snat
spec:
    group: aci.snat
    names:
      kind: NodeInfo
      listKind: NodeInfoList
      plural: nodeinfos
      singular: nodeinfo
    scope: Namespaced
    subresources:
      status: {}
    version: v1
